# Generated by Django 4.2 on 2025-08-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.jagota.com/wp-content/uploads/2023/04/bgr_item2-image-1024x709.jpg', max_length=500),
        ),
    ]
